collections:
  posts:
    output: true
    permalink: /posts/:year/:slug
  archives:
    output: true
    permalink: /archives/:title
  products-presets:
    output: true
    permalink: /shop/presets/:title
  products-guides:
    output: true
    permalink: /shop/guides/:title
